### PR TITLE
guidelines on how to help

### PR DESCRIPTION
**Pull request by brntbeer**
Noticed you didnt have a contributing file.

HOW DO I HELP??

### CODE REVIEW

**Comment by holman** [comment]
What is a "Pull-Request"

**Comment by brntbeer** [comment]
What do you mean "What is a "Pull-Request"" ?

**Comment by holman** [comment]
hyphen

**Comment by brntbeer** [comment]
Common phrasing for people who use github dot com

**Comment by brntbeer** [comment]
No need for a contributing file?

**Pull request closed without merging**
